services:
  web:
    container_name: xtm-fit-web
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - api
  database:
    container_name: xtm-fit-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gym-tracker
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 3s
      retries: 3
    profiles:
      - dev
  api:
    container_name: xtm-fit-api
    build: ./server
    ports:
      - 3333:3333
    depends_on:
      database: 
        condition: service_healthy
        required: false
    