@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@workoutPlanId = 2aefb092-f29d-4b87-a9b9-83ec0682b8a6
@exerciseId = 4526274a-7fea-4321-bdb8-7b50a3fb03ae

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Leonardo Leal",
  "email": "leonardoa.dev@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "leonardoa.dev@gmail.com",
  "password": "123456"
}

###

# @name create_workout_plan
POST {{baseUrl}}/workout-plans
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Peitoral",
  "description": "Planilha com foco para o desenvolvimento do peito",
  "studentId": "1456eb27-12be-4866-99c3-4a3ab7e0f19e" 
}

###

# @name create_exercise
POST {{baseUrl}}/exercises
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Triceps corda"
}

###

# @name assign_exercise_to_workout_plan
POST {{baseUrl}}/workout-plans/{{workoutPlanId}}/exercises
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "exerciseId": "fc740546-161f-4b51-81b1-10841984d1a6",
  "repetitions": 12,
  "sets": 4,
  "weekDay": 4
}

###

# @name fetch_workout_plans
GET {{baseUrl}}/workout-plans
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_week_day_workout_plan_exercises
GET {{baseUrl}}/workout-plans/{{workoutPlanId}}/exercises?weekDay=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_workout_plan_details
GET {{baseUrl}}/workout-plans/{{workoutPlanId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}
